### ISSUE TITLE
Fail-fast on too-big request sizes when possible

### ISSUE THREAD

**Issue by nicmunroe** [Nike-Inc/riposte#37]
Following on to issue #27, we should fail-fast when the request has a content-length greater than the configured max-allowed-request-size value. Currently the failure only happens *after* we've actually received enough bytes to go over the threshold. This change cannot affect chunked encoding requests since they don't include a content-length header.

**Comment by vicbevis** [comment]
Netty4.1 "New and Noteworthy"  documented a improvement:
Better oversized message handling with HttpObjectAggregator

In 4.0, there was no way to reject an oversized HTTP message before a client sends the content even if 100-continue header was present.

This release adds an overridable method called handleOversizedMessage so that a user can perform his or her preferred task. By default, it responds with '413 Request Entity Too Large' response and closed the connection

Should this be helpful for no content-length case?
And any plans to update to netty 4.1?

**Comment by nicmunroe** [comment]
@vicbevis Riposte doesn't use `HttpObjectAggregator` for various reasons (mainly support for chunk-streaming for `ProxyRouterEndpoint`s so we don't have to pull in the full payload, but other reasons as well), so that unfortunately doesn't help.

**Comment by rabeyta** [comment]
fixed in 0.10.0
