### ISSUE TITLE
Any plans to implement a RoutingHandler use JAX-RS annotations?

### ISSUE THREAD

**Issue by VicBing** [Nike-Inc/riposte#39]
There is so many Endpoints exist in a project,it will decrease Endpoint if we use JAX-RS annotations to build path routing, is there any plans to implement a RoutingHandler use JAX-RS annotations ? 

I found this code segment in RoutingHandler below, it will foreach every Endpoint when match a request,maybe it is not a high performance way? I think MultipleMatchingEndpointsException should fire at  application prestarttime and also the foreach should break when find one Endpoint
```java
for (Endpoint<?> endpoint : endpoints) {
    Optional<String> pattern = endpoint.requestMatcher().matchesPath(requestInfo);
    if (pattern.isPresent()) {
        hasPathMatch = true;
        if (endpoint.requestMatcher().matchesMethod(requestInfo)) {
            fullyMatchingEndpoints.add(endpoint);
            matchingPattern = pattern.get();
        }
    }
}
```

**Comment by nicmunroe** [comment]
On the JAX-RS stuff:

It would be possible to create a plugin that would understand JAX-RS annotations and expose them as Riposte endpoints. If someone is motivated to create and maintain such a plugin then it would be welcomed. Just keep in mind that it must be a plugin (separate module) - support for JAX-RS will not be added at the core Riposte level for various reasons. 

This means that the best way forward is probably some helper class (likely with optional classpath scanning) so that your app could simply have its `ServerConfig.appEndpoints()` do something like: `return RiposteJaxRsIntegration.exposeJaxRsAsRiposteEndpoints();` which would return a collection of dynamically generated Riposte `NonblockingEndpoint`s that match whatever JAX-RS annotations it found.

You could make something that works for *basic* JAX-RS annotations pretty quickly, however doing 100% support of the entire JAX-RS spec would likely be an enormous amount of work both initially and in ongoing maintenance, and having partial support might be confusing to users which one of the reasons we haven't pursued this route heavily.

**Comment by nicmunroe** [comment]
On the `RoutingHandler` stuff:

Given that `Matcher` is an interface it's essentially impossible to predetermine whether two endpoints *might* overlap. It might be doable if we got rid of the `Matcher` interface and forced you to always use the current default `SingleMatcher` and `MultiMatcher` implementations (although the wildcard and path parameter support would still make this extremely difficult), however that would artificially restrict what you could do with endpoint matching. For example, since `Matcher` is just an interface, you could create your own implementation that includes header inspections - i.e. you could have two different endpoints that match the same path and method, but use the existence or absence of a header to choose which endpoint is called. Or any other aspect of the request - the `Matcher` interface potentially gives you maximum freedom to choose how requests are mapped onto endpoints.

Simply choosing the first endpoint that matches could lead to some very frustrating and confusing non-deterministic situations, so we decided to always look for the case where multiple endpoints match for a given request and consider that an error case.

We have not yet seen this be a performance issue. If someone runs into a real-world use case where it is a problem then we can look into possible solutions - it's always easier to solve concrete problems from a real issue.

**Comment by VicBing** [comment]
Pretty solved my question,Thanks very much!
